### ISSUE TITLE
Docker-Compose.yml should  be adjusted

### ISSUE THREAD

**Issue by lgehrke6** [muehre/container-manager#11]
Hello, 
first off all i really love the system you build, i tried to "install" it but had one problem ( not with your system but with the docker-compose.yml you supplied us. ) The compose file for PaperSpigot is not correct anymore instead of "Server Type" you only need to type "TYPE". Took me hours... i was wondering why is compose allways starting a vanilla server ... well there we go..
Here the Example Compose file from itzg:
https://github.com/itzg/docker-minecraft-server/blob/master/examples/docker-compose-paper.yml

**Comment by muehre** [comment]
Hey, thanks for commiting this issue 👍 
As i am not maintaining this Project anymore i would appreciate any help.
Just open a PR with your change. Thanks :)

**Comment by ArnaudLier** [comment]
This has been fixed in #13.
