### ISSUE TITLE
Only 'tcp://' or 'unix://' supported.

### ISSUE THREAD

**Issue by Xeroxxx** [muehre/container-manager#12]
Hello,
I'm always getting the following error, no matter where I place the config files.

19:15:08 [WARNING] Exception encountered when loading plugin: DockerizedCraft
com.github.dockerjava.api.exception.DockerClientException: Unsupported protocol scheme found: ''. Only 'tcp://' or 'unix://' supported.

Configs places in plugins/DockerizedCraft/

**Comment by ArnaudLier** [comment]
@Xeroxxx Are you on Linux?

**Comment by Xeroxxx** [comment]
Yes
