### ISSUE TITLE
Project doesn't properly shade bstats

### ISSUE THREAD

**Issue by fr34kyn01535** [muehre/container-manager#2]
I am getting an error when compiling the project with the supplied pom file. I am not really into java and maven so could use some help here :D

`
13:44:05 [WARNING] Exception encountered when loading plugin: DockerizedCraft
9/19/2018 3:44:05 PMjava.lang.NoClassDefFoundError: org/bstats/bungeecord/Metrics
9/19/2018 3:44:05 PM    at de.craftmania.dockerizedcraft.DockerizedCraft.onEnable(DockerizedCraft.java:33)
9/19/2018 3:44:05 PM    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
9/19/2018 3:44:05 PM    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
9/19/2018 3:44:05 PM    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
9/19/2018 3:44:05 PM    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
9/19/2018 3:44:05 PMCaused by: java.lang.ClassNotFoundException: org.bstats.bungeecord.Metrics
9/19/2018 3:44:05 PM    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
9/19/2018 3:44:05 PM    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
9/19/2018 3:44:05 PM    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
9/19/2018 3:44:05 PM    ... 5 more`

**Comment by muehre** [comment]
Yea, looks like shading fails for you.
Why do you need to compile by yourself? :)

**Comment by fr34kyn01535** [comment]
Why did you share the code at all if you dont want people to compile it? True open source means to release source that compiles 😂

I want to obviously test the changes I did to make it work for me.


________________________________
Von: Alexander Mührenberg <notifications@github.com>
Gesendet: Donnerstag, 20. September 2018 20:44
An: DockerizedCraft/Core
Cc: Sven Mawby; Author
Betreff: Re: [DockerizedCraft/Core] Project doesn't properly shade bstats (#2)


Yea, looks like shading fails for you.
Why do you need to compile by yourself? :)

**Comment by fr34kyn01535** [comment]
Fixed it i suppose ;D Running it in intellij everything comes out just fine in the target/assembly folder
