### ISSUE TITLE
What is this licensed under?

### ISSUE THREAD

**Issue by fabianvf** [muehre/container-manager#7]
Super cool project and I'm interested in using it, but I couldn't find any information on what license it is released under. I just wanted to clarify whether that was an oversight or if the project is explicitly not under an open source license.

More info: https://choosealicense.com/no-permission/

Relevant bit:
> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose

**Comment by muehre** [comment]
Feel free to use it however you like. If you do create new cool features make sure to open a PR to enable other people to use it as well ;)
